scriptworker_client: fix TypeError in test_pipe_to_log on python 3.11
```
FAILED tests/test_utils.py::test_pipe_to_log - TypeError: Passing coroutines is forbidden, use tasks explicitly.
```

Per https://docs.python.org/3.11/library/asyncio-task.html#asyncio.wait:
"Changed in version 3.11: Passing coroutine objects to wait() directly is forbidden."