scriptworker_client: fix TypeError on python 3.11
Calling `random.sample()` on a dict_keys object no longer works

```
FAILED tests/test_aio.py::test_LockfileFuture[True] - TypeError: Population must be a sequence.  For dicts or sets, use sorted(d).
FAILED tests/test_aio.py::test_LockfileFuture[False] - TypeError: Population must be a sequence.  For dicts or sets, use sorted(d).
```

https://docs.python.org/3/whatsnew/3.11.html#porting-to-python-3-11